"""
Defaults for config object which is used as a singleton object in project
"""

from yacs.config import CfgNode as CN

_C = CN()

_C.EXPERIMENT = CN()
_C.EXPERIMENT.OUTPUT_FOLDER = "./outputs"
_C.EXPERIMENT.TENSORBOARD_FOLDER = "./runs"
_C.EXPERIMENT.RESUME_TRAINING_ON_RESTART = True
_C.EXPERIMENT.NUM_DATALOADER_WORKERS = 0

_C.DATASET = CN()
_C.DATASET.TRAIN_FILE = ""
_C.DATASET.VALID_FILE = ""
_C.DATASET.TOKENIZER_PREFIX_PATH = ""

_C.TRAIN = CN()
_C.TRAIN.LAST_PRETRAINED_MODEL = ''
_C.TRAIN.SAVE_STEPS = 1000
_C.TRAIN.WEIGHT_DECAY = 0.0
_C.TRAIN.NUM_TRAIN_EPOCHS = 3
_C.TRAIN.LOG_EVERY = 100
_C.TRAIN.LEARNING_RATE = 5e-5
_C.TRAIN.NUM_WARMUP_STEPS = 0
_C.TRAIN.BATCH_SIZE = 32
_C.TRAIN.USE_FP_16 = False
_C.TRAIN.MAX_TRAIN_STEPS = 1000000000000
_C.TRAIN.EVAL_STEPS = 1000
_C.TRAIN.GRADIENT_ACCUMULATION_STEPS = 1
_C.TRAIN.LR_SCHEDULER_TYPE = "linear"
_C.TRAIN.USE_GRADUAL_UNFREEZING = False
_C.TRAIN.UNFREEZING = CN()
_C.TRAIN.UNFREEZING.UNFREEZE_GROUPS = None
_C.TRAIN.UNFREEZING.TRAIN_STEPS_LIST = []
_C.TRAIN.UNFREEZING.LEARNING_RATE_LIST = []
_C.TRAIN.GPT2_PRETRAINED_MODEL = 'gpt2'

cfg = _C  # global singleton object
